#!/usr/bin/env python
# coding=utf-8

import mypwd
import sys

def main():
    argc = len(sys.argv)
    if argc <= 1:
        if len(sys.argv[0]) == 0:
            op = mypwd.public_encrypt(mypwd.KEYSTR, "python")
        else:
            op = mypwd.public_encrypt(mypwd.KEYSTR, sys.argv[0])
        print mypwd.opitem(op, 0)
    elif argc == 2:
        op = mypwd.public_parse(sys.argv[1])
        print mypwd.opitem(op, 1)
    elif argc >= 3:
        op = mypwd.public_encrypt(sys.argv[2], sys.argv[1])
        print mypwd.opitem(op, 1)

if __name__ == "__main__":
    main()

