#!/usr/bin/env python
# coding=utf-8

import sys
import urllib

def ime_callback(str, keyb, dummy):
    ret = []
    for item in str.split("\t+"):
        k,h,v = item.partition("：")
        ret.append((k,"_",int(v)))
    return ret

def parse(keyb, debug=False):
    # check cloud
    url = "http://web.pinyin.sogou.com/api/py?key=938cdfe9e1e39f8dd5da428b1a6a69cb&query="+keyb
    fh = urllib.urlopen(url)
    remotestr = fh.read()
    str = urllib.unquote(remotestr)
    ret = []
    try:
        exec("ret = "+str)
    except Exception, inst:
        print "Exception at "+keyb, "str='"+ str+ "'",type(inst).__name__, inst
        ret = []
    return ret

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print "no argument"
    else:
        keyb = sys.argv[1]
        ret = parse(keyb, debug=True)
        if len(ret) > 0:
            maxlen = len(ret[0][0])
            count = 0
            for k,h,v in ret:
                padding = (maxlen - len(k))/3*2
                count += 1
                if v == -1:
                    print "%2d"%count,"%s %s"%(k,h)
                else:
                    print "%2d"%count,"%s %d %s"%(k,v,h)

